using BlazorWindowManager.ClassLibrary.WindowManagerDialog;

namespace BlazorWindowManager.ClassLibrary.Store.WindowManagerDialog;

public record SetIsMinimizedDialogAction(WindowManagerDialogRecord WindowManagerDialogRecord, bool IsMinimized);